### ISSUE TITLE
to which js file links belongs ?

### ISSUE THREAD

**Issue by molitona** [xnl-h4ck3r/xnLinkFinder#1]
Hi, how to know from which js file each of the links in output.txt comes from ?

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
You need to use the `-orig` flag. As  the help says, you pass this flag if you want the origin of the link to be in the output. It is displayed as `LINK-URL [ORIGIN-URL]` in the file. Bear in mind that a `LINK-URL` may be in the file mutiple times because it was found in multiple origins.
Thanks
Xnl 
🤘

**Comment by xnl-h4ck3r** [comment]
I asume you mean you have the JS files saved locally? If so, you could use trufflehog. For exmaple, something like:
`trufflehog filesystem --directory=~/Where/My/Files/Are`

**Comment by molitona** [comment]
what about if i don't want to download them, is there a solution ?

Jun 16, 2022, 21:22 by ***@***.***:

**Comment by xnl-h4ck3r** [comment]
There is a trufflehog browser extension too that you could use and visit each JS page I guess. Or visit them through Burp and I'm sure there are Burp extensions that will check for secrets
