### ISSUE TITLE
doesnt find links

### ISSUE THREAD

**Issue by sirmalware** [xnl-h4ck3r/xnLinkFinder#10]
greetings the tools for some reason doesn't seem to find any links from the js. it was tested with a link that has known URLs and endpoints but still it didn't find anything.
 below is a sample screenshot
![image](https://user-images.githubusercontent.com/55733240/185348956-0ed58cec-960e-4501-9007-245746fe8932.png)
for comparison purposes here's sample output from linkfinder
![image](https://user-images.githubusercontent.com/55733240/185350704-5a7b3629-47f1-4499-bfa7-484235dd525b.png)

**Comment by xnl-h4ck3r** [comment]
HI @sirmalware 
Thanks for taking the time to raise the issue. 
I noticed your version is 1.1 and the current one is 1.5. Can you update it and try again? I don't understand why any version would return zero results though, and I haven't had that problem before. You can try using -vv option to see if there are any errors happening in the background for any reason.
Also, if you do use xnLinkFinder I would strobgly suggest you use the -d and -sp option because you will get a lot more links back. And alos use -sf to make sure you don't get anything out of scope. Please check out the README doc to understand those parameters and give it another go. Let me know if you have any further problems.
Many thanks
Xnl

**Comment by sirmalware** [comment]
greetings I've just realised that the issue was known before internally and a patch was already issued in another version and that you've closed my issue as a duplicate haha. 
further retesting shows that the issue was indeed fixed.

**Comment by xnl-h4ck3r** [comment]
I'm glad its working now! Thanks again for taking the time to look at the tool and raise any issues though
