### ISSUE TITLE
tool stuck after Processing links in Waymore File /home/kali/waymore/results/example.com/waymore.txt: 

### ISSUE THREAD

**Issue by mehulgupta1** [xnl-h4ck3r/xnLinkFinder#18]
my tool got stuck after this Processing links in Waymore File /home/kali/waymore/results/hackerone.com/waymore.txt:   what to do any solution

**Comment by xnl-h4ck3r** [comment]
Hi @mehulgupta1. Sorry you are having problems with it. Can you show me what command you ran if possible? Thanks

**Comment by xnl-h4ck3r** [comment]
Also, when you say it is stuck, what does the output currently look like? How many lines in waymore.txt?

**Comment by mehulgupta1** [comment]
Hi @xnl-h4ck3r thanks for replying so what is happen is that first i have run waymore for that command is [_**python3 waymore.py -i redbull.com -mode B** ] after running this it downloaded the response in xnl extension then i passes  it to xnlfinder for finding the links in it the command is used for this is [ python3 xnLinkFinder -i ~/Tools/waymore/results/redbull.com -sp https://www.redbull.com -sf redbull.com -o redbull.txt]  after running this it got stuck at { Processing links in Waymore File /home/kali/waymore/results/hackerone.com/waymore.txt:} i have seen jason hadix video where he have found links by passing it to xnlinkfinder

**Comment by mehulgupta1** [comment]
so like if you cant understand now lets we connect on discord so that i can show you in live mode so that we properly understand

**Comment by mehulgupta1** [comment]
my discord id is  mehul003  thank you

**Comment by xnl-h4ck3r** [comment]
Hi @mehulgupta1. I'll connect on discord in a moment, but one thing to note which I'll add herer in case anyone else looks at this issue...
You ran waymore with `-mode B` which means you had the links in waymore.txt, but also downloaded responses in `~/Tools/waymore/results/redbull.com`. When you run xnLinkFinder you'd want to pass the input as `~/Tools/waymore/results/redbull.com` because you want to find links in all the respones aswell as waymore.txt. Also, if you just want to get the links but not crawl anything, you can pass `-d 0` with xnLinkFinder.
