### ISSUE TITLE
XnLinkFinder not working in background using nohup

### ISSUE THREAD

**Issue by elamaran619** [xnl-h4ck3r/xnLinkFinder#24]
When running the XnLinkFinder python file in the background using nohup command, it is not working as expected and hangs.

**Comment by xnl-h4ck3r** [comment]
Hi @elamaran619, thanks for using the tool and taking the time to raise an issue. I have been looking into `nohup` and it seems like a common issue with it not working as expected. Does it worl ok on your system with other tools, or is it just with xnLinkFinder that it's an issue? Thanks

**Comment by elamaran619** [comment]
Hi @xnl-h4ck3r , thanks for the feedback. I have tried XnLinkFinder using `tmux` instead of `nohup` and it is working fine.

**Comment by xnl-h4ck3r** [comment]
Good to hear. Good luck finding some great bugs!

**Comment by Azathothas** [comment]
Similar experience,
I use xnLinkFinder from within a script, on a headless machine with no tty, and it always failed. 
I couldn't see what the error message was, as every time I tried to debug, it worked perfectly fine (because I now had a tty)
This went on for a few weeks, and I almost lost my mind.

Turns out, there's probably some lib/imports which require a tty for xnLinkFinder to work.
And as @elamaran619 pointed out, I now use tmux as it simulates a tty and works.
