### ISSUE TITLE
Support optional creation of separate, wordlist-like output for found links

### ISSUE THREAD

**Issue by cxosmo** [xnl-h4ck3r/xnLinkFinder#6]
Thanks for putting out this great tool @xnl-h4ck3r.

I think it'd be useful to implement an optional feature which does a (small) amount of post-processing on found links, then writing this output to a separate, wordlist-like file in conventional format (e.g. line-separated `example.html`, `api/v1/users` etc). This would allow for easier chaining with other tools (e.g. passing this file to ffuf or Intruder) or creating/appending to custom wordlists using this output.

I'd be happy to submit a pull request which adds this feature if you think it'd be worthwhile (I implemented something similar on a private rework of GerbenJavado's LinkFinder and found it to be handy)!

**Comment by xnl-h4ck3r** [comment]
I've added in piping so that will be in the next release hopefully, so you'll be able to do `python3 xnLinkFinder.py -i evil.com -d 2  | unfurl format "%p%?%q" | sort -u` for example. It will still write the output file, but will pass through to piped processes too. Will that fully give you want you need?

**Comment by cxosmo** [comment]
Sounds good and will work for my use case -- thanks for your efforts on maintaining this great tool!
